### ISSUE TITLE
Not super enough

### ISSUE THREAD

**Issue by navn-r** [MLH-Fellowship/project-damir-super-team#1]
**Enhancement**: Make repo actually 'super'

**Acceptance Criteria**:
- [x] Repo is super

Thanks.

**Comment by dtemir** [comment]
Thank you for your contribution, making this repo actually super.

![alt](https://media0.giphy.com/media/TWrudBaANAXcq2ILMJ/giphy.gif?cid=790b76114c9c3c14dbc0ced231587ade073823b9e81674b8&rid=giphy.gif&ct=g)
